name: Deployment to scheduleanevent.com

# Deployment copied from Scarlet
# https://github.com/SirJosh3917/Scarlet/

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker build . --file Dockerfile --tag ${{ secrets.PRIVATE_CONTAINER_REGISTRY_TAG }}
    
    - name: Docker Login
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
        login-server: ${{ secrets.PRIVATE_CONTAINER_REGISTRY }}
        
    - name: Push
      run: docker push ${{ secrets.PRIVATE_CONTAINER_REGISTRY_TAG }}
    
    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Fetch Deployment Secrets
      uses: Azure/get-keyvault-secrets@v1
      with:
        keyvault: "sirjosh-vault"
        secrets:  'ScarletACRSPNUsername, ScarletACRSPNPassword'
      id: azureSecrets
        
    - name: Deployment
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOYMENT_HOST }}
        username: ${{ secrets.DEPLOYMENT_USERNAME }}
        key: ${{ secrets.DEPLOYMENT_RSA_PRIVATE_KEY }}
        script: ${{ format('{0} ''{1}'' ''{2}''', secrets.DEPLOYMENT_COMMAND, steps.azureSecrets.outputs.ScarletACRSPNUsername, steps.azureSecrets.outputs.ScarletACRSPNPassword) }}
